# -*- coding: utf-8 -*-
"""group project hotel booking EDA Submission Template.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12OSfGPlvmatf89bAf_XYx4gzDxRte5SJ

# **Project Name**    - **Hotel Booking Analysis**

##### **Project Type**    - EDA
##### **Contribution**    - Team
##### **Team Member 1 -** Rakshanda Shaikh
##### **Team Member 2 -** Nirvi Prabhale
##### **Team Member 3 -** Tejesh Khadake
##### **Team Member 4 -** Kalpita Velip

# **Project Summary -**

Have you ever wondered when the best time of year to book a hotel room is? Or the optimal length of stay in order to get the best daily rate? What if you wanted to predict whether or not a hotel was likely to receive a disproportionately high number of special requests? This hotel booking dataset can help you explore those questions!
This data set contains booking information for a city hotel and a resort hotel, and includes information such as when the booking was made, length of stay, the number of adults, children, and/or babies, and the number of available parking spaces, among other things. All personally identifying information has been removed from the data.
Explore and analyze the data to discover important factors that govern the bookings.

# **GitHub Link -**

###Rakshanda's Github Link
https://github.com/Rakshanda19/EDA-HOTEL-BOOKING-/blob/main/group_project_hotel_booking_EDA_Submission_Template.ipynb

###Tejesh's Github Link
https://github.com/tejask108/EDA-Hotel-Booking.git


###Nirvi's Github Link
https://github.com/nirvipc237/HotelBookings-.git

###Kalpita's Github Link
https://github.com/Kalpitavelip/Hotel-Booking-Analysis/tree/main

# **Problem Statement**

When guests are planning the perfect stay, most budget-conscious travellers look for booking hotel rooms months ahead their actual travel date to save money and according to their personal preferences. There are many other factors such as incorrect guest preferences, mishandled reservations, double bookings, cancellation fees. The hotel data analysis can help improve marketing strategies to make the best business decisions and also help the guests make the best booking according to thier preferences.

#### **Define Your Business Objective?**

The core focus of our business objective is to maximize hotel bookings while minimizing cancellations, thereby ensuring a robust customer retention strategy. Our aim is to foster a loyal customer base and extend the duration of guests' stays, ultimately leading to sustained growth and success in the hospitality industry.

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 20 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

"""### Dataset Loading"""

# Load Dataset
#Kalpita
from google.colab import drive
drive.mount('/content/drive')
file_path = "/content/drive/MyDrive/Colab Notebooks/module 2/hotel_bookings.csv"
df1 = pd.read_csv(file_path)

#Rakshanda
df1 = pd.read_csv('/content/Hotel Bookings.csv')

#Nirvi
from google.colab import drive
drive.mount('/content/drive')
df1 ='/content/drive/MyDrive/hotel booking dataset/Hotel Bookings.csv/'
df1 =pd.read_csv('/content/drive/MyDrive/hotel booking dataset/Hotel Bookings.csv')

#Tejesh

df1 =pd.read_csv('/content/Hotel Bookings.csv')

"""### Dataset First View"""

# Dataset First Look
df1.head()

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count
print(f'{df1.shape[0]} rows and {df1.shape[1]} columns')

"""### Dataset Information"""

# Dataset Info
df1.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
df1.duplicated().sum()

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
df1.isna().sum().sort_values(ascending=False)[:5].reset_index().rename(columns={'index':'Columns',0:'Null values'})

# Visualizing the missing values
plt.figure(figsize=(25, 10))
sns.heatmap(df1.isnull(), cbar=False, yticklabels=False,cmap='viridis')
plt.xlabel("Name Of Columns")
plt.title("Places of missing values in column")

"""### What did you know about your dataset?

**1)** Total count of rows are 119390 and columns are 32.

**2)** Overall there are 31994 duplicated values.

**3)** Null values were found  in columns 4 Columns -

 1. Company-Missing Values will be filled with 0.
 2. Agent
    -Missing Values will be filled with 0.
 3. Country
    -Assuming that country was not found while entering the data so the 'Others' option was chosen by the user, missing values will be filled with the object 'Others'
 4. Children
    -Null Value count is only 4 so we can replace it with 0 assuming no children were present.

## ***2. Understanding Your Variables***
"""

# Dataset Columns
df_columns = list(df1.columns)
df_columns

# Dataset Describe
df1.describe(include='all')

"""### Variables Description

**1) hotel :** Hotel(Resort Hotel or City Hotel)

**2) is_canceled :** Value indicating if the booking was canceled (1) or not (0)

**3) lead_time :** Number of days that elapsed between the entering date of the booking into the PMS and the arrival date

**4) arrival_date_year :** Year of arrival date

**5) arrival_date_month :** Month of arrival date

**6) arrival_date_week_number :** Week number of year for arrival date

**7) arrival_date_day_of_month :** Day of arrival date

**8) stays_in_weekend_nights :** Number of weekend nights (Saturday or Sunday) the guest stayed or booked to stay at the hotel

**9) stays_in_week_nights :** Number of week nights (Monday to Friday) the guest stayed or booked to stay at the hotel

**10) adults :** Number of adults

**11) children :** Number of children

**12)babies :** Number of babies

**13) meal :** Type of meal booked. Categories are presented in standard hospitality meal packages:

**14) country :** Country of origin.

**15) market_segment :** Market segment designation. In categories, the term “TA” means “Travel Agents” and “TO” means “Tour Operators”

**16) distribution_channel :** Booking distribution channel. The term “TA” means “Travel Agents” and “TO” means “Tour Operators”

**17) is_repeated_guest :** Value indicating if the booking name was from a repeated guest (1) or not (0)

**18) previous_cancellations :** Number of previous bookings that were cancelled by the customer prior to the current booking

**19) previous_bookings_not_canceled :** Number of previous bookings not cancelled by the customer prior to the current booking

**20) reserved_room_type :** Code of room type reserved. Code is presented instead of designation for anonymity reasons.

**21) assigned_room_type :** Code for the type of room assigned to the booking.

**22) booking_changes :** Number of changes/amendments made to the booking from the moment the booking was entered on the PMS until the moment of check-in or cancellation

**23) deposit_type :** Indication on if the customer made a deposit to guarantee the booking.

**24) agent :** ID of the travel agency that made the booking

**25) company :** ID of the company/entity that made the booking or responsible for paying the booking.

**26) days_in_waiting_list :** Number of days the booking was in the waiting list before it was confirmed to the customer

**27) customer_type :** Type of booking, assuming one of four categories

**28) adr :** Average Daily Rate as defined by dividing the sum of all lodging transactions by the total number of staying nights

**29) required_car_parking_spaces :** Number of car parking spaces required by the customer

**30) total_of_special_requests :** Number of special requests made by the customer (e.g. twin bed or high floor)

**31) reservation_status :** Reservation last status, assuming one of three categories

i) Canceled –** booking was canceled by the customer
ii)Check-Out –** customer has checked in but already departed
ii)No-Show –** customer did not check-in and did inform the hotel of the reason why

**32) reservation_status_date :** Date at which the last status was set. This variable can be used in conjunction with the ReservationStatus to understand when was the booking canceled or when did the customer checked-out of the hotel

### Check Unique Values for each variable.
"""

# Check Unique Values for each variable.
for col in df_columns:
  print(f'Unique values in column {col} are:, {(df1[col].unique())}')

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.
df = df1.copy()

#dropping the duplicate rows
df= df.drop_duplicates()

# converting object type to datetime
df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'], format = '%Y-%m-%d')

# Filling/replacing null values with 0.
null_columns=['company','agent','children']
for col in null_columns:
  df[col].fillna(0,inplace=True)

# Replacing NA values in country with 'others'
df['country'].fillna('others',inplace=True)

#Successfully handled  Null Values
df.isna().sum().sort_values(ascending=False)[:6].reset_index().rename(columns={'index':'Columns',0:'Null values'})

# lets add some new columns
df['total_people'] = df['adults'] + df['babies'] + df['children']
df['total_stay'] = df['stays_in_weekend_nights'] + df['stays_in_week_nights']

# droppping all those rows in which addtion of adlults ,children and babies is 0. That simply means  no bookings were made.
len(df[df['total_people']==0])
df.drop(df[df['total_people']==0].index,inplace=True)

# Checking the final rows and columns
df.shape

"""### What all manipulations have you done and insights you found?

We began by creating a duplicate of the original dataset for our analysis. Our initial step involved cleaning this duplicated dataset, which comprised several stages. Firstly, we removed any duplicated rows to ensure data accuracy. Next, we addressed missing values in the dataset. We then adjusted the data types of columns to their appropriate formats and rectified erroneous data entries. To facilitate enhanced analysis, we introduced new columns.All those rows which indicated that no bookings were made were dropped.All these manipulations reduced the number of rows and columns to 34 rows and 87230 columns.

 Here are the insights that we found:

1) People preferred booking two types of hotels. We found which type was booked more.

2) Guests came from different countries, making the hotel diverse.

3) Guests had different food choices from the menu.

4) Guests could book directly or through different ways.

5)Some guests canceled bookings, and some visited again.

6)Guests could pick the rooms they liked during booking.

7) We used a column called 'adr' to see how well the hotel is doing in terms of money earned.

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

# **Univariate Analysis**

#### Chart - 1 Which are the most preferred hotels?
"""

# Chart - 1 visualization code
df['hotel'].value_counts().plot.pie(explode=[0.05, 0.05], autopct='%1.1f%%', figsize=(10,8),fontsize=20)
plt.title('Bookings per hotel in percentages')

"""##### 1. Why did you pick the specific chart?

**Pie chart enables the audience to see a data comparison at a glance to make an immediate analysis or to understand information quickly even for uninformed audience.The concept of pie slices is used to show the percentages which contains different segments and sectors in which each segment and sector of a pie chart forms a specific portion of the total(percentage).**

##### 2. What is/are the insight(s) found from the chart?

**Number of bookings for City Hotel is 1.6 times more than that of Resort Hotel. City Hotels seems to be more preffered among travellers.**

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**This insight is useful for the stakeholder to check which hotel is performing best and they can invest more capitals in that. There is no such negative growth but stakeholders can focus more on City Hotel to get more booking and icrease the overall revenue.**

#### Chart - 2

**What is the percentange of repeated guests?**
"""

# Chart - 2 visualization code
df['is_repeated_guest'].value_counts().plot.pie(explode=(0.05,0.05),autopct='%1.1f%%',figsize=(12,8),fontsize=20)

plt.title(" Percentage (%) of repeated guests")

"""##### 1. Why did you pick the specific chart?

**Pie chart enables the audience to see a data comparison at a glance to make an immediate analysis or to understand information quickly even for uninformed audience.The concept of pie slices is used to show the percentages which contains different segments and sectors in which each segment and sector of a pie chart forms a specific portion of the total(percentage).**

##### 2. What is/are the insight(s) found from the chart?

**Only a very small percentage (around 4%) of bookings are made by repeated guests whereas large number of guests (96.09%) are new guests.**

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**To improve guest retention, it's important to collect feedback and enhance services. Interestingly, only a small fraction (around 4%) of bookings come from repeat guests, while most (96.09%) are new guests.**

**The insights can help improve the business by enhancing guest experiences. While the low percentage of repeat bookings may be a concern, it also presents an opportunity to focus on strategies that encourage more repeat visits, leading to positive growth.**

#### Chart - 3

**Which room type is more popular among travellers ?**
"""

plt.figure(figsize=(18,8))

#plotting
sns.countplot(x=df['assigned_room_type'],order=df['assigned_room_type'].value_counts().index)
#  set xlabel for the plot
plt.xlabel('Room Type')
# set y label for the plot
plt.ylabel('Count of Room Type')
#set title for the plot
plt.title("Most preferred Room type")

"""##### 1. Why did you pick the specific chart?

**A bar chart is used to visually compare the frequency or count of different categories,so I used this chart. The bar chart helps visualize patterns, trends, and the most common durations of guests' stays in a clear and concise manner.**

##### 2. What is/are the insight(s) found from the chart?

**The "A" room type is the most popular choice among travellers,followed by "D" room type.**

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, the gained insight about Room Type A being the most preferred by guests can help create a positive business impact. To maximize revenue and guest satisfaction, the hotel can focus on increasing the number of Room Type A rooms to meet the high demand. By providing more of the preferred room type, the hotel can attract more guests and potentially increase bookings and revenue.**

#### Chart - 4

**Which agent made the most bookings?**
"""

# Chart - 4 visualization code
# return highest bookings made by agents
highest_bookings= df.groupby(['agent'])['agent'].agg({'count'}).reset_index().rename(columns={'count': "Most_Bookings" }).sort_values(by='Most_Bookings',ascending=False)

 # as agent 0 was NAN value and we replaced it with 0 and indicates no bookings.so droping.
highest_bookings.drop(highest_bookings[highest_bookings['agent']==0].index,inplace=True)

# taking top 10 bookings made by agent
top_ten_highest_bookings=highest_bookings[:10]

top_ten_highest_bookings

#Visualizaing the graph

plt.figure(figsize=(18,8))
sns.barplot(x=top_ten_highest_bookings['agent'],y=top_ten_highest_bookings['Most_Bookings'],order=top_ten_highest_bookings['agent'])
plt.xlabel('Agent No')
plt.ylabel('Number of Bookings')
plt.title("Most Bookings Made by the agent")

"""##### 1. Why did you pick the specific chart?

**A bar chart is used to visually compare the frequency or count of different categories. It helps visualize patterns, trends, and the most common durations of guests' stays in a clear and concise manner.**

##### 2. What is/are the insight(s) found from the chart?

**We can see that agent number 9 has made the most number of bookings followed by agent number 240, 0, 14 and 7.**

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Hotel can offer them bonus for their incredible work and to motivate them. This will help to increase the revenue.Recognizing and rewarding these top agents with bonuses can motivate them to continue their outstanding performance. This can result in increased bookings, revenue, and guest satisfaction, contributing to positive growth for the hotel.**

#### Chart - 5

**Which type of meal is mostly preferred by the guests?**
"""

# Chart - 5 visualization code
# df1['meal'].value_counts().plot.pie(explode=[0.05, 0.05,0.05,0.05,0.05], autopct='%1.1f%%', shadow=True, figsize=(20,15),fontsize=20)
plt.figure(figsize=(18,8))
sns.countplot(x=df1['meal'])
plt.xlabel('Meal Type')
plt.ylabel('Count')
plt.title("Preferred Meal Type")

"""##### 1. Why did you pick the specific chart?

**There are 4 types of meals to be compared and bar chart is used to compare values or counts of different categories, so I used this chart.**

##### 2. What is/are the insight(s) found from the chart?

**From the above chart we can see that BB(Bed and Breakfast) is the most preferred meal type.**

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**The gained insight is that Bed and Breakfast (BB) is the most preferred meal type among guests can indeed help create a positive business impact. With this knowledge, stakeholders can arrange raw materials for the BB meal in advance, ensuring smooth and timely delivery to guests. By focusing on the popular meal type, the hospitality business can enhance guest satisfaction and loyalty, leading to positive reviews and word-of-mouth recommendations, ultimately driving positive business growth.**

#### Chart - 6

**What is the percentage of Cancellation?**
"""

# Chart - 6 visualization code
df['is_canceled'].value_counts().plot.pie(explode=[0.05, 0.05], autopct='%1.1f%%', shadow=True, figsize=(10,8),fontsize=20)
plt.title("Cancellation and non Cancellation")

"""##### 1. Why did you pick the specific chart?

**Pie chart enables the audience to see a data comparison at a glance to make an immediate analysis or to understand information quickly even for uninformed audience.The concept of pie slices is used to show the percentages which contains different segments and sectors in which each segment and sector of a pie chart forms a specific portion of the total(percentage).**

##### 2. What is/are the insight(s) found from the chart?

**Here we can see that around 72.48% bookins are not canceled by guests but around 27.52% bookings are canceled by guests.**

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**This insight will help stakeholders in comparing the cancellation and non cancellation of bookings. With the help of this insight stakeholders can offer rescheduling the bookings instead of cancellation and set a flexible cancellation policy to reduce booking cancellation.**

# **Bivariate Analysis**

#### Chart - 7
**Which hotel has longer waiting time ?**
"""

# Chart - 7 visualization code
#groupping by hotel and taking mean of days in waiting list
waiting_time_df=df.groupby('hotel')['days_in_waiting_list'].mean().reset_index()
# waiting_time_df

#set the plot size
plt.figure(figsize=(10,8))

# plot barchart
sns.barplot(x=waiting_time_df['hotel'],y=waiting_time_df['days_in_waiting_list'])

#set labels
plt.xlabel('Hotel type')
plt.ylabel('waiting time')
plt.title("Waiting time for each hotel type")

"""##### 1. Why did you pick the specific chart?

**A bar chart is used to visually compare the frequency or count of different categories,so I used this chart. The bar chart helps visualize patterns, trends, and the most common durations of guests' stays in a clear and concise manner.**

##### 2. What is/are the insight(s) found from the chart?

**As per the graph, City Hotels has longer waiting period than the Resort Hotels. Thus we can say that City Hotels are much busier than the Resort Hotel.**

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**The gained insight is that the longer waiting period in the City hotel can help create a positive business impact. By addressing the issue and taking steps to decrease the waiting time, such as increasing the number of rooms in the City hotel or converting some rooms from the Resort hotel to City hotel, the hotel can enhance guest satisfaction and improve the overall guest experience.**

#### Chart - 8

**ADR across the different month.**
"""

# Chart - 8 visualization code
#groupby
bookings_by_months_df=df.groupby(['arrival_date_month','hotel'])['adr'].mean().reset_index()
#create month list
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
# it will take the order of the month list in the df along with values
bookings_by_months_df['arrival_date_month']=pd.Categorical(bookings_by_months_df['arrival_date_month'],categories=months,ordered=True)
#sortting
bookings_by_months_df=bookings_by_months_df.sort_values('arrival_date_month')
bookings_by_months_df

# set plot size and plot the line
plt.figure(figsize=(20,8))
sns.lineplot(x=bookings_by_months_df['arrival_date_month'],y=bookings_by_months_df['adr'],hue=bookings_by_months_df['hotel'])

# set lables
plt.title('ADR across each month')
plt.xlabel('Month')
plt.ylabel('ADR')

"""##### 1. Why did you pick the specific chart?

**Line plots, also known as line charts or line graphs, serve several purposes in data visualization due to their ability to illustrate trends and relationships over time or across a continuous range.**

##### 2. What is/are the insight(s) found from the chart?

**For Resrot hotel is ADR is high in the months June,July,August as compared to City Hotels. May be Customers/People wants to spend their Summer vaccation in Resorts Hotels.**

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Yes, the gained insight about the ADR across different months can help create a positive business impact. By identifying the months that generate higher revenue due to higher ADR, stakeholders can proactively prepare and allocate resources to maximize profitability during those periods.**

#### Chart - 9

**How is ADR affecting the lenght of stay?**
"""

# Chart - 9 visualization code

plt.figure(figsize = (12,6))
sns.scatterplot(y = 'total_stay', x = 'adr', data = df)
plt.show()

"""The outlier at total_stays_in_nights=1 affects the accurate interpretation of data visualization and all other values of adr is below 100. So, lets create scatter plot without all the values of adr above 1000."""

plt.figure(figsize = (12,6))
sns.scatterplot(y = 'total_stay', x = 'adr', data = df[df['adr'] < 1000])
plt.show()

"""##### 1. Why did you pick the specific chart?

**Scatter plots are a fundamental and versatile tool in data visualization that are used to explore and display the relationship between two continuous variables. They involve plotting individual data points on a graph, with one variable on the x-axis and another on the y-axis.**

##### 2. What is/are the insight(s) found from the chart?

**As per the scatter plot we can state that the length of stay decreases as ADR increases.**

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**The above insights suggests that when the ADR (average daily rate) goes up, the length of stay tends to go down. This means that higher prices might lead to shorter stays for guests.**
**This insight could have a positive impact on the business if the hotel uses it to find the right balance between pricing and length of stay. However, if prices are raised too much, guests might stay for even shorter periods, leading to negative effects on growth.**

#### Chart - 10

**Which distribution channel contributed more to adr in order to increase the the income.?**
"""

# Chart - 10 visualization code
# group by distribution channel and hotel
distribution_channel_df=df.groupby(['distribution_channel','hotel'])['adr'].mean().reset_index()

# set plot size and plot barchart
plt.figure(figsize=(16,8))
sns.barplot(x='distribution_channel', y='adr', data=distribution_channel_df, hue='hotel')
plt.title('ADR across Distribution channel')

"""*   **Corporate**- These are corporate hotel booing companies which makes bookings
possible.

*   **GDS**-A GDS is a worldwide conduit between travel bookers and suppliers, such as hotels and other accommodation providers. It communicates live product, price and availability data to travel agents and online booking engines, and allows for automated transactions



*   **Direct**- means that bookings are directly made with the respective hotels.

*   **TA/TO**- means that booings are made through travel agents or travel operators.



*   **Undefined**- Bookings are undefined. may be customers made their bookings on arrival

##### 1. Why did you pick the specific chart?

**A bar chart is used to visually compare the frequency or count of different categories,so I used this chart. The bar chart helps visualize patterns, trends, and the most common durations of guests' stays in a clear and concise manner.**

##### 2. What is/are the insight(s) found from the chart?

**From the plot is clear that**
**'Direct' and 'TA/TO' has almost equally contributed in adr in both type of hotels i.e. 'City Hotel' and 'Resort Hotel'.**
**GDS has highly contributed in adr in 'City Hotel' type.**
**GDS needs to increase Resort Hotel bookings.**

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**The gained insights can positively impact the business by highlighting the contribution of different distribution channels to ADR. However, there's a potential negative impact as GDS has contributed significantly to ADR in 'City Hotel' but needs to increase bookings for 'Resort Hotel' to maintain balanced growth.**

#### Chart - 11

**Which distribution channel has the higest cancellation rate?**
"""

# Chart - 11 visualization code
canceled_df=df[df['is_canceled']==1] # 1= canceled

#group by distribution channel
canceled_df=canceled_df.groupby(['distribution_channel','hotel']).size().reset_index().rename(columns={0:'Counts'})
# canceled_df['Percentage']=canceled_df['Counts']*100/df1[df1['is_canceled']==1][0]
canceled_df

#set plot size and plot barchart
plt.figure(figsize=(12,8))
sns.barplot(x='distribution_channel',y='Counts',hue="hotel",data=canceled_df)

# set labels
plt.xlabel('Distribution channel')
plt.ylabel('counts')
plt.title('Cancellation Rate Vs Distribution channel')

"""##### 1. Why did you pick the specific chart?

**A bar chart is used to visually compare the frequency or count of different categories,so we used this chart. The bar chart helps visualize patterns, trends, and the most common durations of guests' stays in a clear and concise manner.**

##### 2. What is/are the insight(s) found from the chart?

**In "TA/TO", City hotels has the high cancellation rate compared to resort hotels.**

**In "direct" both the hotels has almost same cancellation rate.**

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**The insights can positively impact the business by addressing high cancellation rates. However, City hotels face more cancellations in "TA/TO" bookings compared to resort hotels. In "direct" bookings, both hotel types have similar cancellation rates.**

#### Chart - 12

**ADR across different market segment**
"""

# Chart - 12 visualization code

Grupby=df.groupby(['market_segment','hotel','is_canceled'])['adr'].mean().reset_index()   # group by

# set plot size and plto barchart
plt.figure(figsize=(18,6))
sns.barplot(x='market_segment',y='adr',hue='hotel',data=Grupby.sort_values(by='adr',ascending=False))
plt.title('Adr across market segment')

"""##### 1. Why did you pick the specific chart?

**A bar chart is used to visually compare the frequency or count of different categories,so we used this chart. The bar chart helps visualize patterns, trends, and the most common durations of guests' stays in a clear and concise manner.**

##### 2. What is/are the insight(s) found from the chart?

**'Direct' and 'Online TA' are contributing the most in both types of hotels.**

**Aviation segment should focus on increasing the bookings of 'City Hotel'**

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**The insights gained suggest that focusing on increasing bookings for the 'City Hotel' within the aviation segment could lead to a positive business impact. However, there are no insights that indicate negative growth.**

#### Chart - 13

**Which Market Segment has the higest cancellation rate?**
"""

# Chart - 13 visualization code
market_segment_df=df[df['is_canceled']==1]   # canceled=1
market_segment_df
market_segment_df=market_segment_df.groupby(['market_segment','hotel']).size().reset_index().rename(columns={0:'counts'})   # group by

market_segment_df

#set plotsizde and plot barchart
plt.figure(figsize=(20,8))
sns.barplot(x='market_segment',y='counts',hue="hotel",data= market_segment_df)

# set labels
plt.xlabel('market_segment')
plt.ylabel('Counts')
plt.title('Cancellation Rate Vs market_segment')

"""##### 1. Why did you pick the specific chart?

**A bar chart is used to visually compare the frequency or count of different categories,so I used this chart. The bar chart helps visualize patterns, trends, and the most common durations of guests' stays in a clear and concise manner.**

##### 2. What is/are the insight(s) found from the chart?

**'Online T/A' has the highest cancellation in both type of cities.**

**In order to reduce the booking cancellations hotels need to set the refundable/ no refundable and deposit policies policies**.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**The insights we've gathered, like the high cancellations from 'Online TA', can help the business improve. To counter the negative impact of cancellations, hotels should use refundable or non-refundable policies and deposits to reduce cancellations and have a steady income.**

# **Multivariate Analysis**

#### Chart - 14 - Correlation Heatmap
"""

# Correlation Heatmap visualization code

plt.figure(figsize=(18,10))
sns.heatmap(df.corr(numeric_only=True),annot=True)       # Setting the numeric only column to True to avoid warning
plt.title('Co-relation of the columns')

"""##### 1. Why did you pick the specific chart?

**We have used this to visually represent the correlation between pairs of numerical variables. It provides a color-coded matrix that helps identify the strength and direction of relationships between variables.**

##### 2. What is/are the insight(s) found from the chart?

**The insights from the correlation heatmap are:**

**There is a positive correlation between lead_time and total_stay, indicating that longer stays by customers are associated with increased lead times.**

**The number of adults, children, and babies are positively correlated with each other, suggesting that more people staying together tends to result in a higher Average Daily Rate (ADR).**

**There is a strong correlation between being a repeated guest and having previous bookings not canceled, suggesting that repeated guests are less likely to cancel their bookings.**

#### Chart - 15 - Pair Plot
"""

# Pair Plot visualization code

sns.pairplot(df)
plt.show()

"""##### 1. Why did you pick the specific chart?

**A pair plot, also known as a scatterplot matrix, is a type of data visualization that allows you to explore the relationships between multiple pairs of variables in a dataset. It's particularly useful when dealing with datasets that contain multiple quantitative variables.**

##### 2. What is/are the insight(s) found from the chart?

**The insights from the pair plot are:**

**An increase in cancellations is associated with a decrease in total stay, indicating an inverse relationship between these two variables.**

**There is a positive correlation between the total number of people (adults, children, and babies) and the Average Daily Rate (ADR), implying that as the total number of people increases, the ADR also tends to increase.**

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ?
Explain Briefly.

In the hospitality industry, harnessing the power of data helps decision-makers to solve the challenging domain-specific tasks. We have mentioned few pointers which could help in achieveing profitable business.

**1. Focusing more on direct bookings**
    - Hotel's website plays a crucial role. It must have a strong digital identity to attract maximum visitors. Your hotel website should be visually attractive, easy to navigate and above all it should be user-friendly.
    
**2. Promoting good reviews of websites.**
    -  Good reviews can influence a traveller’s booking decision in a big way. This is why it is paramount to strategically position and promote positive guest reviews on thewebsite. It should be visible throughout all the pages till a visitor is done with the whole booking process.

**3. Entice your website visitor with offers or freebies.**
    - Once visitors are on your website, you can give them compelling reasons to book directly with you. Clearly mention the kind of perks they are entitled to if they make direct bookings.

**4. Choosing the most profitable distribution channels.**

**5. Identifying and targeting the most profitable guests.Also taking feedbacks can really help to meet the customer satisfaction.**

**6.Advance Meal Preparation:** Maintain raw materials for BB (Bed and Breakfast) meals in advance to ensure timely service.

**7.Increase City Hotel Capacity:** Expand the number of rooms in City Hotels to reduce waiting times and accommodate more guests.

**8.Market Segment Offers:** Run promotions targeted towards other market segments to increase bookings from those segments.

**9.Manage Waiting Times:** Focus on optimizing operations in City Hotels to reduce waiting times and improve guest experience.

# **Conclusion**

**We’ve drawn many inferences from the survey. Here’s a summary of a few of them:**

**1.** City hotels are the most preferred hotel type by the guests. We can say City hotel is the busiest hotel.

**2.** Repeated guests do not cancel their reservations. Of course there are some exceptions. Also most of the customers are not repeated guests.

**3.** 27.5 % bookings were got cancelled out of all the bookings whereas 72.48% bookings were not cancelled.

**4.** Only 3.9 % people were revisited the hotels. Rest 96.1 % were new guests. Thus retention rate is low.

**5.** BB( Bed & Breakfast) is the most preferred type of meal by the guests.

**6.** Average ADR for city hotel is high as compared to resort hotels. These City hotels are generating more revenue than the resort hotels.

**7.** Booking cancellation rate is high for City hotels which almost 30 %.

**8.** Waiting time period for City hotel is high as compared to resort hotels. That means city hotels are much busier than Resort hotels

**9.** The 'A' room type is most popular choice among the travellers which is followed by room 'D' type.

**10.**  To ensure guest loyalty, a well-structured loyalty points program can be implemented, encouraging guests to return for future stays

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***
"""